name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    # This job runs if it's a push to master or a pull request (not closed)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
        id-token: write
        contents: read # Required to checkout the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true # Keep if your Jekyll site uses Git submodules
          lfs: false       # Keep if your Jekyll site uses Git LFS
          # IMPORTANT: If you commit your *built _site content* to a separate branch
          # (e.g., 'deploy-static') and want to deploy from there, uncomment the line below:
          # ref: deploy-static

      # --- IMPORTANT: All Jekyll/Ruby build steps are intentionally REMOVED from here. ---
      # This workflow assumes your Jekyll site is ALREADY BUILT LOCALLY,
      # and the static HTML/CSS/JS (the contents of your _site folder)
      # are committed directly into the root of the branch being deployed (e.g., 'master').
      # The Azure Static Web Apps action will directly deploy this pre-built content.
      # ----------------------------------------------------------------------------------

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_WATER_0D7F0DB00 }}
          action: "upload"
          # app_location: Points to the root of your pre-built static content within the repository.
          # If the *contents* of your _site folder are directly in your repository's root, use "/".
          app_location: "/"
          api_location: "" # Leave empty for Jekyll (no API backend)
          # output_location: When app_location is "/", output_location should also be "/".
          output_location: "/"
          # CRITICAL: This tells Azure Static Web Apps to SKIP its internal build process.
          # It assumes your content is already built and ready for deployment.
          skip_app_build: true

  # Job for closing Pull Requests (standard for Azure Static Web Apps)
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
