name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
        id-token: write
        contents: read
    # --- Job-level Environment Variables ---
    env:
      # Explicitly set BUNDLE_PATH for Bundler's internal use
      BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      # Explicitly set BUNDLE_GEMFILE to the Gemfile location
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
      # Explicitly set RubyGems' primary gem installation directory (where gems are)
      GEM_HOME: ${{ github.workspace }}/vendor/bundle/ruby/2.7.0 # Based on ls -l output
      # Explicitly set RubyGems' search path for gems (includes GEM_HOME)
      GEM_PATH: ${{ github.workspace }}/vendor/bundle/ruby/2.7.0 # Based on ls -l output
      JEKYLL_ENV: production # Good practice for production builds
    # ------------------------------------------

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # 1. Setup Ruby (using a different action from our previous attempt to ensure freshness)
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Your confirmed local Ruby version
          # Do NOT use bundler-version here; we'll install it manually
          # Do NOT use bundler-cache here

      # 2. Manually install the specific Bundler version
      - name: Install specific Bundler version
        run: |
          gem install bundler -v 2.3.7 --no-document # Installs your Bundler version

      # 3. Install Jekyll and other dependencies
      - name: Install Jekyll and other dependencies
        run: |
          # These commands will automatically use BUNDLE_GEMFILE and BUNDLE_PATH
          # set as job-level environment variables.
          bundle clean --force           # Clean up any old or unused gems
          bundle install --jobs 4 --retry 3 # Install gems

      # 4. Debug Environment and Build Jekyll site
      - name: Debug Environment and Build Jekyll site
        run: |
          echo "--- Environment Variables ---"
          printenv # Dump all environment variables to the log
          echo "--- GEM_HOME: $GEM_HOME ---"
          echo "--- GEM_PATH: $GEM_PATH ---"
          echo "--- BUNDLE_PATH: $BUNDLE_PATH ---"
          echo "--- BUNDLE_GEMFILE: $BUNDLE_GEMFILE ---"
          echo "--- Ruby version check ---"
          ruby -v # Confirm Ruby version
          echo "--- Bundler version check ---"
          bundle -v # Confirm Bundler version
          echo "--- Bundle check (verify gem integrity) ---"
          bundle check # This will explicitly check if Bundler thinks the bundle is complete and correct
          echo "--- Jekyll build.rb file exists check ---"
          ls -l "${{ github.workspace }}/vendor/bundle/ruby/2.7.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb"
          echo "--- Attempting Jekyll build ---"
          bundle exec jekyll build       # Finally, try to build Jekyll

      # 5. Azure Deployment Step (Keep as is)
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_WATER_0D7F0DB00 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "_site"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
